# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Gather Ansible facts
  setup:

- import_role:
    name: linux/common
    tasks_from: apt-repo-microsoft.yml

- import_role:
    name: linux/common
    tasks_from: apt-repo-llvm.yml

- name: Set the names list of the APT packages to be installed
  block:
    - set_fact:
        pkg_names:
          - "clang-7"
          - "clang-format-7"
          - "libssl-dev"
          - "make"
          - "ocaml-native-compilers"
          - "openssl"
          - "pkg-config"
          - "gdb"
          - "ninja-build"
          - "apt-transport-https"
          - "autoconf"
          - "doxygen"
          - "graphviz"
          - "libexpat1-dev"
          - "libtool"
          - "shellcheck"
          - "subversion"
          - "gcc"
          - "g++"

- name: Install all the Open Enclave prerequisites APT packages for development
  apt:
    name: "{{ pkg_names }}"
    state: present
    update_cache: yes
    install_recommends: no

- name: Install CMake 3.13.1
  unarchive:
    src: https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Create CMake symbolic links
  file:
    src: "/usr/local/cmake-3.13.1-Linux-x86_64/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    force: yes
    state: link
  with_items:
    - ccmake
    - cmake
    - cpack
    - ctest
