// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <stdio.h>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the randomSample.edl file.
#include "randomSample_t.h"

// This is the function that the host calls. It prints
// a message in the enclave before calling back out to
// the host to print a message from there too.
int enclave_randomSample()
{   
    int value = 10;
    fprintf(stdout, "Print from the enclave. Host value: %i\n", host_randomSample(&value));   
    return value;
}