# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Install the dkms package
  apt:
    name:
      - "dkms"
    state: present
    update_cache: yes
    install_recommends: no

- name: Ensure aesmd service stopped
  service:
    name: aesmd
    state: stopped

- name: Download Intel SGX DCAP Driver
  get_url:
    url: https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/sgx_linux_x64_driver_dcap_4f32b98.bin
    dest: /tmp/sgx_linux_x64_driver_dcap.bin
    mode: 0755
    timeout: 120
  retries: 3
  when: ansible_distribution_version == "16.04"

- name: Download Intel SGX DCAP Driver
  get_url:
    url: https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1804/sgx_linux_x64_driver_dcap_4f32b98.bin
    dest: /tmp/sgx_linux_x64_driver_dcap.bin
    mode: 0755
    timeout: 120
  retries: 3
  when: ansible_distribution_version != "16.04"

- name: Install the Intel SGX DCAP Driver
  command: /tmp/sgx_linux_x64_driver_dcap.bin

- name: Remove the Intel SGX DCAP Driver installer
  file:
    path: /tmp/sgx_linux_x64_driver_dcap.bin
    state: absent

- name: Ensure aesmd service running
  service:
    name: aesmd
    state: started
    enabled: yes
