# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
opam_bin_url: "https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux"
opam_root: "/usr/local/opam"
ocaml_version: "4.07.0"
cmake_target_version: "3.13.1"
clang_target_version: "8.0.1"

apt_packages:
  - "curl"
  - "clang-8"
  - "clang-format-8"
  - "make"
  - "ninja-build"
  - "shellcheck"
  - "gcc"
  - "g++"
  - "gdb"
  - "libssl-dev"
  - "openssl"
  - "pkg-config"
  - "apt-transport-https"
  - "autoconf"
  - "doxygen"
  - "graphviz"
  - "libexpat1-dev"
  - "libtool"
  - "subversion"
  - "libcurl4-openssl-dev"

apt_arm_packages:
  - "gcc-aarch64-linux-gnu"
  - "g++-aarch64-linux-gnu"
  - "libc6-dev:arm64"
  - "libssl-dev:arm64"

validation_directories:
  - "/usr/local/opam"
  - "/usr/local/opam/{{ ocaml_version }}"
  - "/usr/share/libtool"

validation_files:
  - "/usr/lib/x86_64-linux-gnu/libssl.so"

validation_binaries:
  - "/usr/bin/make"
  - "/usr/local/bin/cmake"
  - "/usr/local/bin/ccmake"
  - "/usr/local/bin/cpack"
  - "/usr/local/bin/ctest"
  - "/usr/bin/dot"
  - "/usr/bin/gcc"
  - "/usr/bin/g++"
  - "/usr/bin/gdb"
  - "/usr/bin/autoconf"
  - "/usr/bin/libtoolize"
  - "/usr/bin/doxygen"
  - "/usr/local/opam/{{ ocaml_version }}/bin/ocaml"
  - "/usr/bin/openssl"
  - "/usr/bin/pkg-config"
  - "/usr/bin/clang-8"
  - "/usr/bin/shellcheck"
  - "/usr/bin/git"
  - "/usr/bin/svn"
